### PR TITLE
remove gitlab runners and managed apps from the setup

### PR DESCRIPTION
**Pull request by Liujingfang1**

### CODE REVIEW

**Comment by Liujingfang1** [comment]
cc @janetkuo @yuwenma @nan-yu @haiyanmeng

**Review by janetkuo — APPROVED** [review]

**Comment by janetkuo** [comment]
This broke the CICD config.

```
$ gcloud builds submit --substitutions=_PROJECT_ID=${PROJECT_ID}
Creating temporary tarball archive of 1237 file(s) totalling 36.0 MiB before compression.
Some files were not included in the source upload.

Check the gcloud log [...] to see which files and the contents of the
default gcloudignore file used (see `$ gcloud topic gcloudignore` to learn
more).

Uploading tarball of [.] to [gs://xxx/source/1601330357.064291-b7476b53f728497e8dde5f0032e89448.tgz]
ERROR: (gcloud.builds.submit) INVALID_ARGUMENT: Request contains an invalid argument.
- '@type': type.googleapis.com/google.rpc.DebugInfo
  detail: |-
    [ORIGINAL ERROR] generic::invalid_argument: invalid build: invalid .steps field: build step #7 - "output-connect-details" depends on "trigger-app-install", which has not been defined
    com.google.net.rpc3.client.RpcClientException: <eye3 title='/ArgoAdminV1.CreateBuild, INVALID_ARGUMENT'/> APPLICATION_ERROR;google.devtools.cloudbuild.v1/ArgoAdminV1.CreateBuild;invalid build: invalid .steps field: build step #7 - "output-connect-details" depends on "trigger-app-install", which has not been defined;AppErrorCode=3;StartTimeMs=1601330364252;unknown;ResFormat=AUTOMATIC;ServerTimeSec=0.141943;LogBytes=256;Non-FailFast;EndUserCredsRequested;EffSecLevel=none;ReqFormat=AUTOMATIC;ReqID=47aa4d9ef00269b4;GlobalID=0;Server=[2002:a17:512:2bc7:b029:cb:80db:4abe]:4001
```

**Comment by Liujingfang1** [comment]
@janetkuo I see where the failure is from. Will update it.

**Pull request merged**
