### PR TITLE
Replace Hipster Shop demo app with updated Online Boutique

### PR DESCRIPTION
**Pull request by michael-intindola**
Removed all Hipster Shop source code from "starter-repos" and replaced with updated Online Boutique source code. 
Also added a banner to Online Boutique that will show the number of transactions processed by Petabank.
Screen Shot 2020-12-10 at 4 58 40 PM

### CODE REVIEW

**Comment by mike-ensor** [comment]
Waiting on a PR to clear though, then this will be applied on top. @bgood can you review as well?

**Comment by bgood** [comment]
@michael-intindola, thank you for the PR, can you please merge in the upstream changes.

**Comment by mike-ensor** [comment]
LGTM

**Review by mike-ensor — APPROVED** [review]

**Comment by michael-intindola** [comment]
Thanks @mike-ensor ! Btw, I just tested the deployment after merging in the upstream changes and it worked :) Cheers

**Pull request merged**
